import Head from "next/head";
import HeaderNavigation from "../components/HeaderNavigation";
import OverlappingTiles from "../components/Promos/OverlappingTiles";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNavigation />

      <OverlappingTiles />
    </div>
  );
}
